In [2]:
!pip install labelme tensorflow opencv-python matplotlib albumentations

You should consider upgrading via the 'c:\users\viji0\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [3]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
    Running setup.py install for tensorflow-gpu: started
    Running setup.py install for tensorflow-gpu: finished with status 'error'


  ERROR: Command errored out with exit status 1:
   command: 'c:\users\viji0\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\viji0\\AppData\\Local\\Temp\\pip-install-jl2icshs\\tensorflow-gpu\\setup.py'"'"'; __file__='"'"'C:\\Users\\viji0\\AppData\\Local\\Temp\\pip-install-jl2icshs\\tensorflow-gpu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\viji0\AppData\Local\Temp\pip-wheel-n3ik1mce'
       cwd: C:\Users\viji0\AppData\Local\Temp\pip-install-jl2icshs\tensorflow-gpu\
  Complete output (17 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\viji0\AppData\Local\Temp\pip-install-jl2icshs\tensorflow-gpu\setup.py", line 37, in <module>
      raise Exception(TF_REMOVAL_WARNING)
  Exception:
  
  The "tensorflow-gpu

In [4]:
import os
import time
import uuid
import cv2

In [5]:
IMAGES_PATH = os.path.join('data','images')
number_images=30

In [9]:

cap = cv2.VideoCapture(0)  # Ensure the correct camera index

for imgnum in range(number_images):
    print('collecting image {}'.format(imgnum))
    ret, frame = cap.read()
    if not ret:
        print("Failed to capture image")
        continue
    imgname = os.path.join(IMAGES_PATH, f'{str(uuid.uuid1())}.jpg')
    cv2.imwrite(imgname, frame)
    cv2.imshow('frame', frame)
    time.sleep(0.5)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()


collecting image 0


error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:1301: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'


In [ ]:
!labelme

In [6]:
import os

# Set the matplotlib backend before importing anything else
os.environ['MPLBACKEND'] = 'agg'

# Now you can import other modules
import matplotlib
matplotlib.use('agg')  # 'agg' is a non-interactive backend suitable for script and automated use



In [7]:
!pip install --upgrade labelme

Requirement already up-to-date: labelme in c:\users\viji0\appdata\local\programs\python\python39\lib\site-packages (5.5.0)


You should consider upgrading via the 'c:\users\viji0\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [8]:
import labelme


ModuleNotFoundError: No module named 'labelme'

In [ ]:
import os

# Set the matplotlib backend to a supported one
os.environ['MPLBACKEND'] = 'agg'  # or 'tkagg', 'qt5agg', etc.

try:
    import labelme
    print("labelme imported successfully")
except Exception as e:
    print(f"Error importing labelme: {e}")

# Run labelme (as a script or from the command line)
os.system('labelme')


In [ ]:
!labelme

In [9]:
import tensorflow as tf


In [10]:
pip install --upgrade tensorflow

Note: you may need to restart the kernel to use updated packages.


In [11]:
!pip list

Package                      Version
---------------------------- -------------------
absl-py                      2.1.0
albucore                     0.0.12
albumentations               1.4.10
annotated-types              0.7.0
astunparse                   1.6.3
beautifulsoup4               4.12.3
cachetools                   5.3.3
certifi                      2024.6.2
charset-normalizer           3.3.2
colorama                     0.4.6
coloredlogs                  15.0.1
contourpy                    1.2.1
cycler                       0.12.1
filelock                     3.15.4
flatbuffers                  24.3.25
fonttools                    4.53.0
gast                         0.6.0
gdown                        5.2.0
google-auth                  2.31.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
grpcio                       1.64.1
h5py                         3.11.0
humanfriendly                10.0
idna                         3.7
imageio                    

You should consider upgrading via the 'c:\users\viji0\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [12]:
import json


In [13]:
import numpy as np

In [14]:

from matplotlib import pyplot as plt

In [15]:
# Avoid OOM errors by setting GPU Memory Consumption Growth
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus: 
    tf.config.experimental.set_memory_growth(gpu, True)

In [16]:
gpus = tf.config.list_physical_devices('GPU')

In [17]:
images = tf.data.Dataset.list_files('data\\images\\*.jpg')

In [18]:
images.as_numpy_iterator().next()

b'data\\images\\750e1769-39c5-11ef-affe-88a9b281cd13.jpg'

In [19]:
def load_image(x): 
    byte_img = tf.io.read_file(x)
    img = tf.io.decode_jpeg(byte_img)
    return img

In [20]:
images = images.map(load_image)

In [21]:
images.as_numpy_iterator().next()

array([[[52, 34, 22],
        [53, 35, 23],
        [56, 33, 25],
        ...,
        [82, 74, 72],
        [87, 77, 76],
        [92, 82, 81]],

       [[53, 35, 23],
        [53, 35, 23],
        [55, 32, 24],
        ...,
        [78, 70, 67],
        [84, 74, 72],
        [91, 81, 79]],

       [[53, 35, 23],
        [52, 34, 22],
        [53, 30, 22],
        ...,
        [74, 67, 61],
        [82, 73, 68],
        [92, 83, 78]],

       ...,

       [[33, 34, 28],
        [32, 33, 27],
        [32, 31, 26],
        ...,
        [25, 27, 26],
        [25, 27, 26],
        [26, 28, 27]],

       [[34, 33, 28],
        [33, 32, 27],
        [32, 31, 26],
        ...,
        [27, 29, 26],
        [27, 29, 26],
        [27, 29, 26]],

       [[33, 32, 27],
        [32, 31, 26],
        [31, 30, 25],
        ...,
        [30, 32, 29],
        [29, 31, 28],
        [29, 31, 28]]], dtype=uint8)

In [22]:
type(images)

tensorflow.python.data.ops.map_op._MapDataset

In [23]:
image_generator = images.batch(4).as_numpy_iterator()

In [24]:
plot_images = image_generator.next()

In [25]:
import matplotlib.pyplot as plt

# Set the backend explicitly
plt.switch_backend('TkAgg')  # Choose appropriate backend here

fig, ax = plt.subplots(ncols=4, figsize=(20,20))
for idx, image in enumerate(plot_images):
    ax[idx].imshow(image) 
plt.show()

In [ ]:
60*.7 #42 to train

In [ ]:
60*0.15 #9 to test and 9 to val

In [ ]:
42+9+9

In [26]:
pip install --upgrade albumentations

Note: you may need to restart the kernel to use updated packages.


In [27]:
import os
for folder in ['train','test','val']:
    for file in os.listdir(os.path.join('data', folder, 'images')):
        
        filename = file.split('.')[0]+'.json'
        existing_filepath = os.path.join('data','labels', filename)
        if os.path.exists(existing_filepath): 
            new_filepath = os.path.join('data',folder,'labels',filename)
            os.replace(existing_filepath, new_filepath) 

In [28]:
import albumentations as alb

In [29]:
augmentor = alb.Compose([alb.RandomCrop(width=450, height=450), 
                         alb.HorizontalFlip(p=0.5), 
                         alb.RandomBrightnessContrast(p=0.2),
                         alb.RandomGamma(p=0.2), 
                         alb.RGBShift(p=0.2), 
                         alb.VerticalFlip(p=0.5)], 
                       bbox_params=alb.BboxParams(format='albumentations', 
                                                  label_fields=['class_labels']))

In [30]:
import os
img = cv2.imread(os.path.join('data','train', 'images','2922d620-3915-11ef-98f5-88a9b281cd13.jpg'))

In [31]:
!pip install --upgrade opencv-python

Requirement already up-to-date: opencv-python in c:\users\viji0\appdata\local\programs\python\python39\lib\site-packages (4.10.0.84)


You should consider upgrading via the 'c:\users\viji0\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [32]:
import cv2

In [33]:
import json
with open(os.path.join('data', 'train', 'labels', '2922d620-3915-11ef-98f5-88a9b281cd13.json'), 'r') as f:
    label = json.load(f)

In [34]:
label['shapes'][0]['points']

[[232.7906976744186, 162.96511627906978],
 [376.3953488372093, 335.6395348837209]]

In [35]:
coords = [0,0,0,0]
coords[0] = label['shapes'][0]['points'][0][0]
coords[1] = label['shapes'][0]['points'][0][1]
coords[2] = label['shapes'][0]['points'][1][0]
coords[3] = label['shapes'][0]['points'][1][1]

In [36]:
coords

[232.7906976744186, 162.96511627906978, 376.3953488372093, 335.6395348837209]

In [37]:
coords = list(np.divide(coords, [640,480,640,480]))

In [38]:
coords

[0.3637354651162791,
 0.3395106589147287,
 0.5881177325581396,
 0.6992490310077518]

In [39]:
augmented = augmentor(image=img, bboxes=[coords], class_labels=['face'])

In [40]:
augmented['bboxes'][0][2:]

(0.5297674418604652, 0.6622997416020672)

In [41]:
augmented['bboxes']

[(0.21064599483204133,
  0.2785788113695091,
  0.5297674418604652,
  0.6622997416020672)]

In [42]:
cv2.rectangle(augmented['image'], 
              tuple(np.multiply(augmented['bboxes'][0][:2], [450,450]).astype(int)),
              tuple(np.multiply(augmented['bboxes'][0][2:], [450,450]).astype(int)), 
                    (255,0,0), 2)

plt.imshow(augmented['image'])

In [43]:
for partition in ['train','test','val']: 
    for image in os.listdir(os.path.join('data', partition, 'images')):
        img = cv2.imread(os.path.join('data', partition, 'images', image))

        coords = [0,0,0.00001,0.00001]
        label_path = os.path.join('data', partition, 'labels', f'{image.split(".")[0]}.json')
        if os.path.exists(label_path):
            with open(label_path, 'r') as f:
                label = json.load(f)

            coords[0] = label['shapes'][0]['points'][0][0]
            coords[1] = label['shapes'][0]['points'][0][1]
            coords[2] = label['shapes'][0]['points'][1][0]
            coords[3] = label['shapes'][0]['points'][1][1]
            coords = list(np.divide(coords, [640,480,640,480]))

        try: 
            for x in range(60):
                augmented = augmentor(image=img, bboxes=[coords], class_labels=['face'])
                cv2.imwrite(os.path.join('aug_data', partition, 'images', f'{image.split(".")[0]}.{x}.jpg'), augmented['image'])

                annotation = {}
                annotation['image'] = image

                if os.path.exists(label_path):
                    if len(augmented['bboxes']) == 0: 
                        annotation['bbox'] = [0,0,0,0]
                        annotation['class'] = 0 
                    else: 
                        annotation['bbox'] = augmented['bboxes'][0]
                        annotation['class'] = 1
                else: 
                    annotation['bbox'] = [0,0,0,0]
                    annotation['class'] = 0 


                with open(os.path.join('aug_data', partition, 'labels', f'{image.split(".")[0]}.{x}.json'), 'w') as f:
                    json.dump(annotation, f)

        except Exception as e:
            print(e)

In [44]:
train_images = tf.data.Dataset.list_files('aug_data\\train\\images\\*.jpg', shuffle=False)
train_images = train_images.map(load_image)
train_images = train_images.map(lambda x: tf.image.resize(x, (120,120)))
train_images = train_images.map(lambda x: x/255)

In [45]:
test_images = tf.data.Dataset.list_files('aug_data\\test\\images\\*.jpg', shuffle=False)
test_images = test_images.map(load_image)
test_images = test_images.map(lambda x: tf.image.resize(x, (120,120)))
test_images = test_images.map(lambda x: x/255)

In [46]:
val_images = tf.data.Dataset.list_files('aug_data\\val\\images\\*.jpg', shuffle=False)
val_images = val_images.map(load_image)
val_images = val_images.map(lambda x: tf.image.resize(x, (120,120)))
val_images = val_images.map(lambda x: x/255)

In [47]:
train_images.as_numpy_iterator().next()

array([[[0.7264093 , 0.66268384, 0.79270834],
        [0.7357843 , 0.6759804 , 0.81311274],
        [0.71960783, 0.6647059 , 0.80196077],
        ...,
        [0.11329657, 0.05183823, 0.16066177],
        [0.18125   , 0.09993873, 0.20404412],
        [0.26446077, 0.1370098 , 0.2541054 ]],

       [[0.7167892 , 0.6746324 , 0.7908088 ],
        [0.71813726, 0.67585784, 0.8000613 ],
        [0.72205883, 0.6789216 , 0.8122549 ],
        ...,
        [0.08357843, 0.03658088, 0.17634805],
        [0.17071079, 0.08388481, 0.19479166],
        [0.44368872, 0.30202207, 0.409375  ]],

       [[0.6887255 , 0.6519608 , 0.75784314],
        [0.7102941 , 0.66568625, 0.7848039 ],
        [0.7284926 , 0.67359066, 0.8108456 ],
        ...,
        [0.11078431, 0.09050245, 0.17879902],
        [0.1278799 , 0.08780637, 0.18553922],
        [0.25582108, 0.16893382, 0.28198528]],

       ...,

       [[0.6544118 , 0.7050858 , 0.8432598 ],
        [0.721201  , 0.76617646, 0.8922794 ],
        [0.7420956 , 0

In [48]:
def load_labels(label_path):
    with open(label_path.numpy(), 'r', encoding = "utf-8") as f:
        label = json.load(f)
        
    return [label['class']], label['bbox']

In [49]:
train_labels = tf.data.Dataset.list_files('aug_data\\train\\labels\\*.json', shuffle=False)
train_labels = train_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [50]:
test_labels = tf.data.Dataset.list_files('aug_data\\test\\labels\\*.json', shuffle=False)
test_labels = test_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [51]:
val_labels = tf.data.Dataset.list_files('aug_data\\val\\labels\\*.json', shuffle=False)
val_labels = val_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [52]:
train_labels.as_numpy_iterator().next()

(array([1], dtype=uint8),
 array([0.3018 , 0.02896, 0.7886 , 0.78   ], dtype=float16))

In [53]:
len(train_images), len(train_labels), len(test_images), len(test_labels), len(val_images), len(val_labels)

(2520, 2520, 540, 540, 540, 540)

In [54]:
train = tf.data.Dataset.zip((train_images, train_labels))
train = train.shuffle(5000)
train = train.batch(8)
train = train.prefetch(4)

In [55]:
test = tf.data.Dataset.zip((test_images, test_labels))
test = test.shuffle(1300)
test = test.batch(8)
test = test.prefetch(4)

In [56]:
val = tf.data.Dataset.zip((val_images, val_labels))
val = val.shuffle(1000)
val = val.batch(8)
val = val.prefetch(4)

In [57]:
train.as_numpy_iterator().next()[1]


(array([[1],
        [1],
        [1],
        [1],
        [0],
        [0],
        [1],
        [1]], dtype=uint8),
 array([[0.     , 0.315  , 0.269  , 0.6934 ],
        [0.1998 , 0.276  , 0.5127 , 0.658  ],
        [0.     , 0.2361 , 0.0718 , 0.7593 ],
        [0.4995 , 0.297  , 0.8857 , 0.787  ],
        [0.     , 0.     , 0.     , 0.     ],
        [0.     , 0.     , 0.     , 0.     ],
        [0.558  , 0.06696, 1.     , 0.779  ],
        [0.3208 , 0.3252 , 0.6685 , 0.7905 ]], dtype=float16))

In [58]:
data_samples = train.as_numpy_iterator()

In [59]:
res = data_samples.next()

In [60]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(ncols=4, figsize=(20,20))

for idx in range(4): 
    sample_image = res[0][idx].copy()  # Make a copy to avoid modifying the original array
    sample_coords = res[1][1][idx]
    
    sample_image = cv2.UMat(sample_image)  # Convert to cv::UMat object

    cv2.rectangle(sample_image, 
                  tuple(np.multiply(sample_coords[:2], [120,120]).astype(int)),
                  tuple(np.multiply(sample_coords[2:], [120,120]).astype(int)), 
                  (255,0,0), 2)

    ax[idx].imshow(sample_image.get())  # Convert back to numpy array for imshow

plt.show()


In [61]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, Dense, GlobalMaxPooling2D
from tensorflow.keras.applications import VGG16

In [62]:
vgg = VGG16(include_top=False)

In [63]:
vgg.summary()

Model: "vgg16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, None, None, 3)       │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_conv1 (Conv2D)                │ (None, None, None, 64)      │           1,792 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_conv2 (Conv2D)                │ (None, None, None, 64)      │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block1_pool (MaxPooling2D)           │ (None, None, None, 64)      │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_conv1 (Conv2D)                │ (None, None, None, 128)     │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_conv2 (Conv2D)                │ (None, None, None, 128)     │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block2_pool (MaxPooling2D)           │ (None, None, None, 128)     │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv1 (Conv2D)                │ (None, None, None, 256)     │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv2 (Conv2D)                │ (None, None, None, 256)     │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_conv3 (Conv2D)                │ (None, None, None, 256)     │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block3_pool (MaxPooling2D)           │ (None, None, None, 256)     │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv1 (Conv2D)                │ (None, None, None, 512)     │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv2 (Conv2D)                │ (None, None, None, 512)     │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_conv3 (Conv2D)                │ (None, None, None, 512)     │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block4_pool (MaxPooling2D)           │ (None, None, None, 512)     │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv1 (Conv2D)                │ (None, None, None, 512)     │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv2 (Conv2D)                │ (None, None, None, 512)     │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_conv3 (Conv2D)                │ (None, None, None, 512)     │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ block5_pool (MaxPooling2D)           │ (None, None, None, 512)     │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 14,714,688 (56.13 MB)

 Trainable params: 14,714,688 (56.13 MB)

 Non-trainable params: 0 (0.00 B)

In [64]:
def build_model(): 
    input_layer = Input(shape=(120,120,3))
    
    vgg = VGG16(include_top=False)(input_layer)

    # Classification Model  
    f1 = GlobalMaxPooling2D()(vgg)
    class1 = Dense(2048, activation='relu')(f1)
    class2 = Dense(1, activation='sigmoid')(class1)
    
    # Bounding box model
    f2 = GlobalMaxPooling2D()(vgg)
    regress1 = Dense(2048, activation='relu')(f2)
    regress2 = Dense(4, activation='sigmoid')(regress1)
    
    facetracker = Model(inputs=input_layer, outputs=[class2, regress2])
    return facetracker

In [65]:
facetracker = build_model()

In [66]:
facetracker.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)    │ (None, 120, 120, 3)       │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ vgg16 (Functional)            │ (None, 3, 3, 512)         │      14,714,688 │ input_layer_1[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ global_max_pooling2d          │ (None, 512)               │               0 │ vgg16[0][0]                │
│ (GlobalMaxPooling2D)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ global_max_pooling2d_1        │ (None, 512)               │               0 │ vgg16[0][0]                │
│ (GlobalMaxPooling2D)          │                           │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense (Dense)                 │ (None, 2048)              │       1,050,624 │ global_max_pooling2d[0][0] │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_2 (Dense)               │ (None, 2048)              │       1,050,624 │ global_max_pooling2d_1[0]… │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_1 (Dense)               │ (None, 1)                 │           2,049 │ dense[0][0]                │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ dense_3 (Dense)               │ (None, 4)                 │           8,196 │ dense_2[0][0]              │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 16,826,181 (64.19 MB)

 Trainable params: 16,826,181 (64.19 MB)

 Non-trainable params: 0 (0.00 B)

In [67]:
X, y = train.as_numpy_iterator().next()

In [68]:
X.shape

(8, 120, 120, 3)

In [69]:
classes, coords = facetracker.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 572ms/step


In [70]:
classes, coords

(array([[0.47853962],
        [0.40045094],
        [0.5169549 ],
        [0.41520184],
        [0.44749755],
        [0.3951699 ],
        [0.44021446],
        [0.4839391 ]], dtype=float32),
 array([[0.5209563 , 0.4903573 , 0.42640874, 0.4495195 ],
        [0.50211704, 0.4941932 , 0.4552778 , 0.33756012],
        [0.5574913 , 0.4327545 , 0.49161503, 0.40620467],
        [0.57426167, 0.44198763, 0.45224383, 0.41504642],
        [0.5955683 , 0.5907381 , 0.43534186, 0.43362468],
        [0.48342285, 0.56795585, 0.501469  , 0.35261002],
        [0.59889317, 0.5294616 , 0.47673082, 0.3745628 ],
        [0.5226345 , 0.43105295, 0.5441723 , 0.4386797 ]], dtype=float32))

In [71]:
batches_per_epoch = len(train)
lr_decay = (1./0.75 -1)/batches_per_epoch

In [72]:
batches_per_epoch = len(train)
lr_decay = (1./0.75 -1)/batches_per_epoch

In [73]:
opt = tf.keras.optimizers.Adam(learning_rate=0.0001, decay=lr_decay)

C:\Users\viji0\anaconda3\lib\site-packages\keras\src\optimizers\base_optimizer.py:33: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(


In [74]:
import tensorflow as tf

def localization_loss(y_true, yhat):
    # Cast y_true to float32 to match yhat
    y_true = tf.cast(y_true, tf.float32)

    delta_coord = tf.reduce_sum(tf.square(y_true[:, :2] - yhat[:, :2]))

    h_true = y_true[:, 3] - y_true[:, 1]
    w_true = y_true[:, 2] - y_true[:, 0]

    h_pred = yhat[:, 3] - yhat[:, 1]
    w_pred = yhat[:, 2] - yhat[:, 0]

    delta_size = tf.reduce_sum(tf.square(w_true - w_pred) + tf.square(h_true - h_pred))

    return delta_coord + delta_size


In [75]:
classloss = tf.keras.losses.BinaryCrossentropy()
regressloss = localization_loss

In [76]:
localization_loss(y[1], coords)

<tf.Tensor: shape=(), dtype=float32, numpy=4.907795>

In [77]:
classloss(y[0], classes)

<tf.Tensor: shape=(), dtype=float32, numpy=0.7582746>

In [78]:
regressloss(y[1], coords)

<tf.Tensor: shape=(), dtype=float32, numpy=4.907795>

In [83]:
#this is code from git
class FaceTracker(Model): 
    def __init__(self, eyetracker,  **kwargs): 
        super().__init__(**kwargs)
        self.model = eyetracker

    def compile(self, opt, classloss, localizationloss, **kwargs):
        super().compile(**kwargs)
        self.closs = classloss
        self.lloss = localizationloss
        self.opt = opt
    
    def train_step(self, batch, **kwargs): 
        
        X, y = batch
        
        with tf.GradientTape() as tape: 
            classes, coords = self.model(X, training=True)
            
            batch_classloss = self.closs(y[0], classes)
            batch_localizationloss = self.lloss(tf.cast(y[1], tf.float32), coords)
            
            total_loss = batch_localizationloss+0.5*batch_classloss
            
            grad = tape.gradient(total_loss, self.model.trainable_variables)
        
        opt.apply_gradients(zip(grad, self.model.trainable_variables))
        
        return {"total_loss":total_loss, "class_loss":batch_classloss, "regress_loss":batch_localizationloss}
    
    def test_step(self, batch, **kwargs): 
        X, y = batch
        
        classes, coords = self.model(X, training=False)
        
        batch_classloss = self.closs(y[0], classes)
        batch_localizationloss = self.lloss(tf.cast(y[1], tf.float32), coords)
        total_loss = batch_localizationloss+0.5*batch_classloss
        
        return {"total_loss":total_loss, "class_loss":batch_classloss, "regress_loss":batch_localizationloss}
        
    def call(self, X, **kwargs): 
        return self.model(X, **kwargs)

In [80]:
model = FaceTracker(facetracker)

In [81]:
model.compile(opt, classloss, regressloss)

In [82]:
logdir='logs'

In [83]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)

In [84]:
hist = model.fit(train, epochs=10, validation_data=val, callbacks=[tensorboard_callback])

Epoch 1/10
315/315 ━━━━━━━━━━━━━━━━━━━━ 552s 2s/step - class_loss: 0.0832 - regress_loss: 0.3929 - total_loss: 0.4345 - val_class_loss: 5.8739e-04 - val_regress_loss: 0.0154 - val_total_loss: 0.0157
Epoch 2/10
315/315 ━━━━━━━━━━━━━━━━━━━━ 536s 2s/step - class_loss: 0.0081 - regress_loss: 0.0921 - total_loss: 0.0962 - val_class_loss: 1.7909e-04 - val_regress_loss: 0.1151 - val_total_loss: 0.1152
Epoch 3/10
315/315 ━━━━━━━━━━━━━━━━━━━━ 448s 1s/step - class_loss: 0.0177 - regress_loss: 0.0722 - total_loss: 0.0811 - val_class_loss: 7.9012e-04 - val_regress_loss: 0.0361 - val_total_loss: 0.0365
Epoch 4/10
315/315 ━━━━━━━━━━━━━━━━━━━━ 389s 1s/step - class_loss: 3.5058e-04 - regress_loss: 0.0185 - total_loss: 0.0186 - val_class_loss: 3.4194e-05 - val_regress_loss: 0.0118 - val_total_loss: 0.0118
Epoch 5/10
315/315 ━━━━━━━━━━━━━━━━━━━━ 462s 1s/step - class_loss: 1.7442e-04 - regress_loss: 0.0128 - total_loss: 0.0129 - val_class_loss: 1.6057e-04 - val_regress_loss: 0.1090 - val_total_loss: 0.10

In [79]:
#code from gpt
class FaceTracker(Model):
    def __init__(self, eyetracker, **kwargs):
        super().__init__(**kwargs)
        self.model = eyetracker

    def compile(self, opt, classloss, localizationloss, **kwargs):
        super().compile(**kwargs)
        self.closs = classloss
        self.lloss = localizationloss
        self.opt = opt

    def train_step(self, batch, **kwargs):
        X, (class_labels, bbox_labels) = batch  # Assuming labels are returned as tuples from Dataset.zip

        with tf.GradientTape() as tape:
            classes, coords = self.model(X, training=True)

            # Ensure class_labels and bbox_labels have defined shapes
            class_labels = tf.reshape(class_labels, [-1])  # Reshape if necessary
            bbox_labels = tf.reshape(bbox_labels, [-1, 4])  # Adjust shape according to your bbox format

            batch_classloss = self.closs(class_labels, classes)
            batch_localizationloss = self.lloss(bbox_labels, coords)

            total_loss = batch_localizationloss + 0.5 * batch_classloss

        gradients = tape.gradient(total_loss, self.model.trainable_variables)
        self.opt.apply_gradients(zip(gradients, self.model.trainable_variables))

        return {"total_loss": total_loss, "class_loss": batch_classloss, "regress_loss": batch_localizationloss}

    def test_step(self, batch, **kwargs):
        X, (class_labels, bbox_labels) = batch

        classes, coords = self.model(X, training=False)

        # Ensure class_labels and bbox_labels have defined shapes
        class_labels = tf.reshape(class_labels, [-1])  # Reshape if necessary
        bbox_labels = tf.reshape(bbox_labels, [-1, 4])  # Adjust shape according to your bbox format

        batch_classloss = self.closs(class_labels, classes)
        batch_localizationloss = self.lloss(bbox_labels, coords)
        total_loss = batch_localizationloss + 0.5 * batch_classloss

        return {"total_loss": total_loss, "class_loss": batch_classloss, "regress_loss": batch_localizationloss}

    def call(self, X, **kwargs):
        return self.model(X, **kwargs)


In [95]:
hist.history

{'class_loss': [0.0010780824813991785,
  0.0007989193545654416,
  0.0003679728542920202,
  0.00010200431279372424,
  0.001555697526782751,
  0.0003836893883999437,
  3.809180634561926e-05,
  0.000136027330881916,
  4.99020388815552e-05,
  0.10816887766122818],
 'regress_loss': [0.09415149688720703,
  0.03229382634162903,
  0.021535731852054596,
  0.011968124657869339,
  0.01239493303000927,
  0.016580918803811073,
  0.0034873776603490114,
  0.1370164453983307,
  0.010491165332496166,
  0.08780595660209656],
 'total_loss': [0.09469053894281387,
  0.0326932854950428,
  0.021719718351960182,
  0.012019126676023006,
  0.013172782026231289,
  0.016772763803601265,
  0.0035064236726611853,
  0.1370844542980194,
  0.01051611639559269,
  0.14189039170742035],
 'val_class_loss': [0.01805703714489937,
  0.00010155777999898419,
  0.0014597470872104168,
  0.004023621324449778,
  0.00011884369450854138,
  0.011704081669449806,
  1.1582530532905366e-05,
  3.9832787024352e-07,
  4.527160490397364e-05

In [85]:
fig, ax = plt.subplots(ncols=3, figsize=(20,5))

ax[0].plot(hist.history['total_loss'], color='teal', label='loss')
ax[0].plot(hist.history['val_total_loss'], color='orange', label='val loss')
ax[0].title.set_text('Loss')
ax[0].legend()

ax[1].plot(hist.history['class_loss'], color='teal', label='class loss')
ax[1].plot(hist.history['val_class_loss'], color='orange', label='val class loss')
ax[1].title.set_text('Classification Loss')
ax[1].legend()

ax[2].plot(hist.history['regress_loss'], color='teal', label='regress loss')
ax[2].plot(hist.history['val_regress_loss'], color='orange', label='val regress loss')
ax[2].title.set_text('Regression Loss')
ax[2].legend()

plt.show()

In [86]:
test_data = test.as_numpy_iterator()

In [87]:
test_sample = test_data.next()

In [88]:
yhat = facetracker.predict(test_sample[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step


In [89]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(ncols=4, figsize=(20,20))
for idx in range(4): 
    sample_image = test_sample[0][idx].copy()  # Make a writable copy
    sample_coords = yhat[1][idx]
    
    if yhat[0][idx] > 0.9:
        cv2.rectangle(sample_image, 
                      tuple(np.multiply(sample_coords[:2], [120,120]).astype(int)),
                      tuple(np.multiply(sample_coords[2:], [120,120]).astype(int)), 
                      (255,0,0), 2)
    
    ax[idx].imshow(sample_image)

plt.show()


In [2]:
from tensorflow.keras.models import load_model

In [91]:
facetracker.save('facetracker.h5')

In [ ]:
facetracker = load_model('facetracker.h5')

In [ ]:
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import ipywidgets as widgets

# Initialize video capture
cap = cv2.VideoCapture(0)  # Use 0 for default camera, 1 for external camera

# Check if camera opened successfully
if not cap.isOpened():
    print("Error: Could not open camera.")
    exit()

# Set up Matplotlib figure for inline display
plt.figure(figsize=(8, 6))

# Function to process and display each frame
def process_frame(frame):
    # Preprocess frame (crop and resize)
    frame = frame[50:500, 50:500, :]
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    resized = tf.image.resize(rgb, (120, 120))
    
    # Example placeholder for yhat
    yhat = (0.8, [0.1, 0.2, 0.7, 0.8])  # Example values, replace with actual yhat output
    
    # Process yhat if it meets the condition
    if yhat[0] > 0.5:
        sample_coords = yhat[1]
        if len(sample_coords) >= 4:  # Ensure sample_coords has at least 4 elements
            # Calculate coordinates based on prediction
            top_left = tuple(np.multiply(sample_coords[:2], [450, 450]).astype(int))
            bottom_right = tuple(np.multiply(sample_coords[2:], [450, 450]).astype(int))
            
            # Draw rectangles
            cv2.rectangle(frame, top_left, bottom_right, (255, 0, 0), 2)
            cv2.rectangle(frame, (top_left[0], top_left[1] - 30), (top_left[0] + 80, top_left[1]), (255, 0, 0), -1)
            
            # Draw text
            cv2.putText(frame, 'face', (top_left[0], top_left[1] - 5), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
    
    # Display the frame using Matplotlib
    plt.imshow(frame)
    plt.axis('off')
    plt.show()
    clear_output(wait=True)


# Widget for user interaction (exit button)
button = widgets.Button(description="Stop")
display(button)

# Event handler for button click
def on_button_clicked(b):
    cap.release()
    plt.close()
    clear_output(wait=True)

button.on_click(on_button_clicked)

# Main loop for video capture and processing
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    
    # Process and display frame
    process_frame(frame)

# Release resources
cap.release()
cv2.destroyAllWindows()
